/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.Teofilo.Atividades;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;

/**
 *
 * @author User
 */
public class AtividadesJF extends javax.swing.JFrame {

    //variaveis que representam o id das atividades no banco de dados
    private static final int PRIMEIRA_TABELA = 1;
    private static final int SEGUNDA_TABELA = 2;
    private static final int TERCEIRA_TABELA = 3;
    private static final int QUARTA_TABELA = 4;

    private static final int QTD_QUADROS = 4;
    JScrollPane[] jsp = new JScrollPane[QTD_QUADROS];
    JPanel[] jspp = new JPanel[QTD_QUADROS];
    JTextField[] titulos = new JTextField[QTD_QUADROS];

    private final Point point = new Point();
    List<Atividade> atividades;
    List<Cartao> cartoes;

    /**
     * Creates new form AtividadesJF
     */
    public AtividadesJF() {
        initComponents();
        jsp[0] = jsp_0;
        jsp[1] = jsp_1;
        jsp[2] = jsp_2;
        jsp[3] = jsp_3;
        jspp[0] = jspp_0;
        jspp[1] = jspp_1;
        jspp[2] = jspp_2;
        jspp[3] = jspp_3;
        titulos[0] = atv1;
        titulos[1] = atv2;
        titulos[2] = atv3;
        titulos[3] = atv4;
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFundo = new javax.swing.JPanel();
        jp = new javax.swing.JPanel();
        atv1 = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        jsp_0 = new javax.swing.JScrollPane();
        jspp_0 = new javax.swing.JPanel();
        removeBtn = new javax.swing.JButton();
        jp_1 = new javax.swing.JPanel();
        atv2 = new javax.swing.JTextField();
        addBtn_1 = new javax.swing.JButton();
        jsp_1 = new javax.swing.JScrollPane();
        jspp_1 = new javax.swing.JPanel();
        removeBtn1 = new javax.swing.JButton();
        jp_2 = new javax.swing.JPanel();
        atv3 = new javax.swing.JTextField();
        addBtn_2 = new javax.swing.JButton();
        jsp_2 = new javax.swing.JScrollPane();
        jspp_2 = new javax.swing.JPanel();
        removeBtn2 = new javax.swing.JButton();
        jp_3 = new javax.swing.JPanel();
        atv4 = new javax.swing.JTextField();
        addBtn_3 = new javax.swing.JButton();
        jsp_3 = new javax.swing.JScrollPane();
        jspp_3 = new javax.swing.JPanel();
        removeBtn3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        panelFundo.setBackground(new java.awt.Color(255, 255, 255));
        panelFundo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jp.setBackground(new java.awt.Color(255, 255, 255));
        jp.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));

        atv1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        atv1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        atv1.setBorder(null);
        atv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atv1ActionPerformed(evt);
            }
        });
        atv1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                atv1KeyPressed(evt);
            }
        });

        addBtn.setBackground(new java.awt.Color(255, 255, 255));
        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/Teofilo/IMG/1x/ic_control_point_24px.png"))); // NOI18N
        addBtn.setBorder(null);
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        jsp_0.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jsp_0.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jsp_0.setViewportView(jspp_0);

        javax.swing.GroupLayout jspp_0Layout = new javax.swing.GroupLayout(jspp_0);
        jspp_0.setLayout(jspp_0Layout);
        jspp_0Layout.setHorizontalGroup(
            jspp_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 194, Short.MAX_VALUE)
        );
        jspp_0Layout.setVerticalGroup(
            jspp_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );

        jsp_0.setViewportView(jspp_0);

        removeBtn.setBackground(new java.awt.Color(255, 255, 255));
        removeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/Teofilo/IMG/1x/ic_delete_24px.png"))); // NOI18N
        removeBtn.setBorder(null);
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpLayout = new javax.swing.GroupLayout(jp);
        jp.setLayout(jpLayout);
        jpLayout.setHorizontalGroup(
            jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(atv1)
            .addGroup(jpLayout.createSequentialGroup()
                .addComponent(addBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(removeBtn))
            .addComponent(jsp_0)
        );
        jpLayout.setVerticalGroup(
            jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLayout.createSequentialGroup()
                .addComponent(atv1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsp_0, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addBtn)
                    .addComponent(removeBtn)))
        );

        jp_1.setBackground(new java.awt.Color(255, 255, 255));
        jp_1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));

        atv2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        atv2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        atv2.setBorder(null);
        atv2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                atv2KeyPressed(evt);
            }
        });

        addBtn_1.setBackground(new java.awt.Color(255, 255, 255));
        addBtn_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/Teofilo/IMG/1x/ic_control_point_24px.png"))); // NOI18N
        addBtn_1.setBorder(null);
        addBtn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtn_1ActionPerformed(evt);
            }
        });

        jsp_1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        javax.swing.GroupLayout jspp_1Layout = new javax.swing.GroupLayout(jspp_1);
        jspp_1.setLayout(jspp_1Layout);
        jspp_1Layout.setHorizontalGroup(
            jspp_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 194, Short.MAX_VALUE)
        );
        jspp_1Layout.setVerticalGroup(
            jspp_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );

        jsp_1.setViewportView(jspp_1);

        removeBtn1.setBackground(new java.awt.Color(255, 255, 255));
        removeBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/Teofilo/IMG/1x/ic_delete_24px.png"))); // NOI18N
        removeBtn1.setBorder(null);
        removeBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_1Layout = new javax.swing.GroupLayout(jp_1);
        jp_1.setLayout(jp_1Layout);
        jp_1Layout.setHorizontalGroup(
            jp_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(atv2)
            .addGroup(jp_1Layout.createSequentialGroup()
                .addComponent(addBtn_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(removeBtn1))
            .addComponent(jsp_1)
        );
        jp_1Layout.setVerticalGroup(
            jp_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_1Layout.createSequentialGroup()
                .addComponent(atv2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsp_1, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addBtn_1)
                    .addComponent(removeBtn1)))
        );

        jp_2.setBackground(new java.awt.Color(255, 255, 255));
        jp_2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));

        atv3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        atv3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        atv3.setBorder(null);
        atv3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                atv3KeyPressed(evt);
            }
        });

        addBtn_2.setBackground(new java.awt.Color(255, 255, 255));
        addBtn_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/Teofilo/IMG/1x/ic_control_point_24px.png"))); // NOI18N
        addBtn_2.setBorder(null);
        addBtn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtn_2ActionPerformed(evt);
            }
        });

        jsp_2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        javax.swing.GroupLayout jspp_2Layout = new javax.swing.GroupLayout(jspp_2);
        jspp_2.setLayout(jspp_2Layout);
        jspp_2Layout.setHorizontalGroup(
            jspp_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 194, Short.MAX_VALUE)
        );
        jspp_2Layout.setVerticalGroup(
            jspp_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );

        jsp_2.setViewportView(jspp_2);

        removeBtn2.setBackground(new java.awt.Color(255, 255, 255));
        removeBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/Teofilo/IMG/1x/ic_delete_24px.png"))); // NOI18N
        removeBtn2.setBorder(null);
        removeBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_2Layout = new javax.swing.GroupLayout(jp_2);
        jp_2.setLayout(jp_2Layout);
        jp_2Layout.setHorizontalGroup(
            jp_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(atv3)
            .addGroup(jp_2Layout.createSequentialGroup()
                .addComponent(addBtn_2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(removeBtn2))
            .addComponent(jsp_2)
        );
        jp_2Layout.setVerticalGroup(
            jp_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_2Layout.createSequentialGroup()
                .addComponent(atv3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsp_2, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addBtn_2)
                    .addComponent(removeBtn2)))
        );

        jp_3.setBackground(new java.awt.Color(255, 255, 255));
        jp_3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));

        atv4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        atv4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        atv4.setBorder(null);
        atv4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                atv4KeyPressed(evt);
            }
        });

        addBtn_3.setBackground(new java.awt.Color(255, 255, 255));
        addBtn_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/Teofilo/IMG/1x/ic_control_point_24px.png"))); // NOI18N
        addBtn_3.setBorder(null);
        addBtn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtn_3ActionPerformed(evt);
            }
        });

        jsp_3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        javax.swing.GroupLayout jspp_3Layout = new javax.swing.GroupLayout(jspp_3);
        jspp_3.setLayout(jspp_3Layout);
        jspp_3Layout.setHorizontalGroup(
            jspp_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 194, Short.MAX_VALUE)
        );
        jspp_3Layout.setVerticalGroup(
            jspp_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );

        jsp_3.setViewportView(jspp_3);

        removeBtn3.setBackground(new java.awt.Color(255, 255, 255));
        removeBtn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/Teofilo/IMG/1x/ic_delete_24px.png"))); // NOI18N
        removeBtn3.setBorder(null);
        removeBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtn3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_3Layout = new javax.swing.GroupLayout(jp_3);
        jp_3.setLayout(jp_3Layout);
        jp_3Layout.setHorizontalGroup(
            jp_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(atv4)
            .addGroup(jp_3Layout.createSequentialGroup()
                .addComponent(addBtn_3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(removeBtn3))
            .addComponent(jsp_3)
        );
        jp_3Layout.setVerticalGroup(
            jp_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_3Layout.createSequentialGroup()
                .addComponent(atv4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsp_3, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addBtn_3)
                    .addComponent(removeBtn3)))
        );

        javax.swing.GroupLayout panelFundoLayout = new javax.swing.GroupLayout(panelFundo);
        panelFundo.setLayout(panelFundoLayout);
        panelFundoLayout.setHorizontalGroup(
            panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jp_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jp_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jp_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFundoLayout.setVerticalGroup(
            panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jp_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp_2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/Teofilo/IMG/1x/ic_cancel_18px.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Atividades");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        Point p = this.getLocation();
        this.setLocation(p.x + evt.getX() - point.x, p.y + evt.getY() - point.y);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        point.x = evt.getX();
        point.y = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        adicionarTarefa(PRIMEIRA_TABELA, atv1.getName());
    }//GEN-LAST:event_addBtnActionPerformed

    private void addBtn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtn_1ActionPerformed
        adicionarTarefa(SEGUNDA_TABELA, atv2.getName());
    }//GEN-LAST:event_addBtn_1ActionPerformed

    private void addBtn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtn_2ActionPerformed
        adicionarTarefa(TERCEIRA_TABELA, atv3.getName());
    }//GEN-LAST:event_addBtn_2ActionPerformed

    private void addBtn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtn_3ActionPerformed
        adicionarTarefa(QUARTA_TABELA, atv4.getName());
    }//GEN-LAST:event_addBtn_3ActionPerformed

    private void atv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atv1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atv1ActionPerformed

    private void atv1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_atv1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            atualizarTitulo(PRIMEIRA_TABELA);
        }
    }//GEN-LAST:event_atv1KeyPressed

    private void atv2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_atv2KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            atualizarTitulo(SEGUNDA_TABELA);
        }
    }//GEN-LAST:event_atv2KeyPressed

    private void atv3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_atv3KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            atualizarTitulo(TERCEIRA_TABELA);
        }
    }//GEN-LAST:event_atv3KeyPressed

    private void atv4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_atv4KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            atualizarTitulo(QUARTA_TABELA);
        }
    }//GEN-LAST:event_atv4KeyPressed

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        new RemoverCartaoJD(null, true, PRIMEIRA_TABELA).setVisible(true);
        atualizarBotoes();
    }//GEN-LAST:event_removeBtnActionPerformed

    private void removeBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtn1ActionPerformed
        new RemoverCartaoJD(null, true, SEGUNDA_TABELA).setVisible(true);
        atualizarBotoes();
    }//GEN-LAST:event_removeBtn1ActionPerformed

    private void removeBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtn2ActionPerformed
        new RemoverCartaoJD(null, true, TERCEIRA_TABELA).setVisible(true);
        atualizarBotoes();
    }//GEN-LAST:event_removeBtn2ActionPerformed

    private void removeBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtn3ActionPerformed
        new RemoverCartaoJD(null, true, QUARTA_TABELA).setVisible(true);
        atualizarBotoes();
    }//GEN-LAST:event_removeBtn3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtividadesJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtividadesJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtividadesJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtividadesJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AtividadesJF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton addBtn_1;
    private javax.swing.JButton addBtn_2;
    private javax.swing.JButton addBtn_3;
    private javax.swing.JTextField atv1;
    private javax.swing.JTextField atv2;
    private javax.swing.JTextField atv3;
    private javax.swing.JTextField atv4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jp;
    private javax.swing.JPanel jp_1;
    private javax.swing.JPanel jp_2;
    private javax.swing.JPanel jp_3;
    private javax.swing.JScrollPane jsp_0;
    private javax.swing.JScrollPane jsp_1;
    private javax.swing.JScrollPane jsp_2;
    private javax.swing.JScrollPane jsp_3;
    private javax.swing.JPanel jspp_0;
    private javax.swing.JPanel jspp_1;
    private javax.swing.JPanel jspp_2;
    private javax.swing.JPanel jspp_3;
    private javax.swing.JPanel panelFundo;
    private javax.swing.JButton removeBtn;
    private javax.swing.JButton removeBtn1;
    private javax.swing.JButton removeBtn2;
    private javax.swing.JButton removeBtn3;
    // End of variables declaration//GEN-END:variables

    private void init() {
        //inicializa atividades
        atividades = new AtividadeDAO().findAll();
        int count = 0;
        for (Atividade a : atividades) {
            titulos[count].setText(a.getNome());
            count++;
            if (count == QTD_QUADROS) {
                break;
            }
        }
        //carrega botoes do banco de dados
        atualizarBotoes();

    }

    private void adicionarTarefa(int tabela, String tituloTabela) {
        String nomeDoBotao = "";
        nomeDoBotao = JOptionPane.showInputDialog(null, "Digite o nome da nova tarefa: ", tituloTabela, JOptionPane.QUESTION_MESSAGE);
        if (nomeDoBotao == null) {
            return;
        } else if (nomeDoBotao.equals("")) {
            return;
        }
        /*
            fazer metodo para verificar se ja existe um cartao criado com o mesmo nome no db
            caso exista: impedir o usuario de concluir a ação.
         */

        //salvar no db esse botao novo
        Cartao c = new Cartao();
        c.setCor("-2696737"); //cor padrao do botao em rgb
        c.setID_LISTA_ATIVIDADES(tabela);
        c.setTitulo(nomeDoBotao);
        if (new CartaoDAO().addCartao(c)) {
            atualizarBotoes();
        } else {
            JOptionPane.showMessageDialog(null, "Ocorreu um problema ao tentar adicionar Cartao ao Banco de Dados.");
        }
    }

    /*
     metodo que abre o botao clicado
     */
    private void tarefaBotao(ActionEvent evt, JButton botao) {
        new Thread(() -> {
            botao.setText("Abrindo...");
            botao.setForeground(Color.BLUE);
            CartaoJD jd = new CartaoJD(null, true, botao);
            jd.setVisible(true);
            if (jd.atualizarExterno()) {
                atualizarBotoes();
            }
        }).start();
    }

    /*
     metodo que popula as listas com todos os botoes existentes no banco de dados
     */
    private synchronized void atualizarBotoes() {
        List<JButton> botoes1 = new ArrayList<>();
        List<JButton> botoes2 = new ArrayList<>();
        List<JButton> botoes3 = new ArrayList<>();
        List<JButton> botoes4 = new ArrayList<>();
        //busca todos os cartoes no banco de dados
        cartoes = new CartaoDAO().findAll();
        for (Cartao c : cartoes) {
            String entrega = "";
            if (c.getEntrega() != null) {
                entrega = c.getEntrega();
            }
            //cria os botoes para o cartao
            JButton botao = new JButton("<html><center>" + c.getTitulo() + "<br>" + entrega + "</center></html>");
            botao.setFont(new Font("Arial", Font.BOLD, 14));
            //defini o name do botao como ID do cartao para passar por parametro para o CartaoJD
            botao.setName(Integer.toString(c.getId()));
            //defini a cor do botao atravez da cor obtida no c.getColor()
            botao.setBackground(new Color(Integer.parseInt(c.getCor())));
            //coloca o botao criado em sua respectiva lista
            switch (c.getID_LISTA_ATIVIDADES()) {
                case PRIMEIRA_TABELA:
                    botoes1.add(botao);
                    break;
                case SEGUNDA_TABELA:
                    botoes2.add(botao);
                    break;
                case TERCEIRA_TABELA:
                    botoes3.add(botao);
                    break;
                case QUARTA_TABELA:
                    botoes4.add(botao);
                    break;
                default:
                    return;
            }
        }
        //preenche as listas com os botoes
        for (int x = 0; x < QTD_QUADROS; x++) {
            switch (x) {
                case 0:
                    preencherLista(botoes1, x);
                    break;
                case 1:
                    preencherLista(botoes2, x);
                    break;
                case 2:
                    preencherLista(botoes3, x);
                    break;
                default:
                    preencherLista(botoes4, x);
                    break;
            }
        }
    }

    private void preencherLista(List<JButton> botoes, int x) {
        jspp[x].removeAll();
        jsp[x].setViewportView(jspp[x]);
        for (JButton botao : botoes) {
            //cria um evento para o click no botao
            botao.addActionListener((java.awt.event.ActionEvent evt) -> {
                tarefaBotao(evt, botao);
            });
            //defini o tamanho do botao
            botao.setSize(jspp[x].getSize().width, 50);
            //defini bordas
            botao.setBorder(null);
            //defini o local onde o botao deve aparecer
            if (jspp[x].getComponentCount() > 0) {
                botao.setLocation(0, jspp[x].getComponent(jspp[x].getComponentCount() - 1).getLocation().y + jspp[x].getComponent(jspp[x].getComponentCount() - 1).getHeight() + 5);
            } else {
                botao.setLocation(0, 5);
            }
            //adiciona o botao ao jspp
            jspp[x].add(botao);
            //redimenciona o jspp caso tenha muios botoes
            if (jspp[x].getComponentCount() > 0) {
                Dimension d = jspp[x].getSize();
                int height = jspp[x].getComponent(jspp[x].getComponentCount() - 1).getLocation().y;
                height += jspp[x].getComponent(jspp[x].getComponentCount() - 1).getSize().height + 5;
                d.height = height;
                jspp[x].setPreferredSize(d);
            }
            //seta viewport
            jsp[x].setViewportView(jspp[x]);
        }
    }

    /*
        procedimento responsavel por atualizar os titulos
        status : funcionando
     */
    private void atualizarTitulo(int i) {
        titulos[i - 1].setForeground(Color.blue);
        if (!new AtividadeDAO().updateAtividade(i, titulos[i - 1].getText())) {
            JOptionPane.showMessageDialog(null, "Ocorreu um problema ao tentar atualizar o titulo da atividade.");
            titulos[i - 1].setForeground(Color.red);
        } else {
            titulos[i - 1].setForeground(Color.black);
        }
    }

}
